---
# This playbook create all namespaces necessary for cluster deployment
- name: Create simple namespace
  k8s:
      name: test
      api_version: v1
      context: admooh-dev-local
      kind: Namespace
      state: present